# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bios/CLionProjects/Game/OpenGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bios/CLionProjects/Game/OpenGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bios/CLionProjects/Game/OpenGL/CMakeFiles /home/bios/CLionProjects/Game/OpenGL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bios/CLionProjects/Game/OpenGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

Core/Camera.o: Core/Camera.cpp.o
.PHONY : Core/Camera.o

# target to build an object file
Core/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Camera.cpp.o
.PHONY : Core/Camera.cpp.o

Core/Camera.i: Core/Camera.cpp.i
.PHONY : Core/Camera.i

# target to preprocess a source file
Core/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Camera.cpp.i
.PHONY : Core/Camera.cpp.i

Core/Camera.s: Core/Camera.cpp.s
.PHONY : Core/Camera.s

# target to generate assembly for a file
Core/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Camera.cpp.s
.PHONY : Core/Camera.cpp.s

Core/EBO.o: Core/EBO.cpp.o
.PHONY : Core/EBO.o

# target to build an object file
Core/EBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/EBO.cpp.o
.PHONY : Core/EBO.cpp.o

Core/EBO.i: Core/EBO.cpp.i
.PHONY : Core/EBO.i

# target to preprocess a source file
Core/EBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/EBO.cpp.i
.PHONY : Core/EBO.cpp.i

Core/EBO.s: Core/EBO.cpp.s
.PHONY : Core/EBO.s

# target to generate assembly for a file
Core/EBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/EBO.cpp.s
.PHONY : Core/EBO.cpp.s

Core/FBO.o: Core/FBO.cpp.o
.PHONY : Core/FBO.o

# target to build an object file
Core/FBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/FBO.cpp.o
.PHONY : Core/FBO.cpp.o

Core/FBO.i: Core/FBO.cpp.i
.PHONY : Core/FBO.i

# target to preprocess a source file
Core/FBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/FBO.cpp.i
.PHONY : Core/FBO.cpp.i

Core/FBO.s: Core/FBO.cpp.s
.PHONY : Core/FBO.s

# target to generate assembly for a file
Core/FBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/FBO.cpp.s
.PHONY : Core/FBO.cpp.s

Core/Mesh.o: Core/Mesh.cpp.o
.PHONY : Core/Mesh.o

# target to build an object file
Core/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Mesh.cpp.o
.PHONY : Core/Mesh.cpp.o

Core/Mesh.i: Core/Mesh.cpp.i
.PHONY : Core/Mesh.i

# target to preprocess a source file
Core/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Mesh.cpp.i
.PHONY : Core/Mesh.cpp.i

Core/Mesh.s: Core/Mesh.cpp.s
.PHONY : Core/Mesh.s

# target to generate assembly for a file
Core/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Mesh.cpp.s
.PHONY : Core/Mesh.cpp.s

Core/Model.o: Core/Model.cpp.o
.PHONY : Core/Model.o

# target to build an object file
Core/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Model.cpp.o
.PHONY : Core/Model.cpp.o

Core/Model.i: Core/Model.cpp.i
.PHONY : Core/Model.i

# target to preprocess a source file
Core/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Model.cpp.i
.PHONY : Core/Model.cpp.i

Core/Model.s: Core/Model.cpp.s
.PHONY : Core/Model.s

# target to generate assembly for a file
Core/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Model.cpp.s
.PHONY : Core/Model.cpp.s

Core/Texture.o: Core/Texture.cpp.o
.PHONY : Core/Texture.o

# target to build an object file
Core/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Texture.cpp.o
.PHONY : Core/Texture.cpp.o

Core/Texture.i: Core/Texture.cpp.i
.PHONY : Core/Texture.i

# target to preprocess a source file
Core/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Texture.cpp.i
.PHONY : Core/Texture.cpp.i

Core/Texture.s: Core/Texture.cpp.s
.PHONY : Core/Texture.s

# target to generate assembly for a file
Core/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/Texture.cpp.s
.PHONY : Core/Texture.cpp.s

Core/VAO.o: Core/VAO.cpp.o
.PHONY : Core/VAO.o

# target to build an object file
Core/VAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/VAO.cpp.o
.PHONY : Core/VAO.cpp.o

Core/VAO.i: Core/VAO.cpp.i
.PHONY : Core/VAO.i

# target to preprocess a source file
Core/VAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/VAO.cpp.i
.PHONY : Core/VAO.cpp.i

Core/VAO.s: Core/VAO.cpp.s
.PHONY : Core/VAO.s

# target to generate assembly for a file
Core/VAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/VAO.cpp.s
.PHONY : Core/VAO.cpp.s

Core/VBO.o: Core/VBO.cpp.o
.PHONY : Core/VBO.o

# target to build an object file
Core/VBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/VBO.cpp.o
.PHONY : Core/VBO.cpp.o

Core/VBO.i: Core/VBO.cpp.i
.PHONY : Core/VBO.i

# target to preprocess a source file
Core/VBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/VBO.cpp.i
.PHONY : Core/VBO.cpp.i

Core/VBO.s: Core/VBO.cpp.s
.PHONY : Core/VBO.s

# target to generate assembly for a file
Core/VBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/VBO.cpp.s
.PHONY : Core/VBO.cpp.s

Core/shaderClass.o: Core/shaderClass.cpp.o
.PHONY : Core/shaderClass.o

# target to build an object file
Core/shaderClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/shaderClass.cpp.o
.PHONY : Core/shaderClass.cpp.o

Core/shaderClass.i: Core/shaderClass.cpp.i
.PHONY : Core/shaderClass.i

# target to preprocess a source file
Core/shaderClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/shaderClass.cpp.i
.PHONY : Core/shaderClass.cpp.i

Core/shaderClass.s: Core/shaderClass.cpp.s
.PHONY : Core/shaderClass.s

# target to generate assembly for a file
Core/shaderClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/shaderClass.cpp.s
.PHONY : Core/shaderClass.cpp.s

Core/stb/stb_image.o: Core/stb/stb_image.cpp.o
.PHONY : Core/stb/stb_image.o

# target to build an object file
Core/stb/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/stb/stb_image.cpp.o
.PHONY : Core/stb/stb_image.cpp.o

Core/stb/stb_image.i: Core/stb/stb_image.cpp.i
.PHONY : Core/stb/stb_image.i

# target to preprocess a source file
Core/stb/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/stb/stb_image.cpp.i
.PHONY : Core/stb/stb_image.cpp.i

Core/stb/stb_image.s: Core/stb/stb_image.cpp.s
.PHONY : Core/stb/stb_image.s

# target to generate assembly for a file
Core/stb/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Core/stb/stb_image.cpp.s
.PHONY : Core/stb/stb_image.cpp.s

glad/src/glad.o: glad/src/glad.c.o
.PHONY : glad/src/glad.o

# target to build an object file
glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad/src/glad.c.o
.PHONY : glad/src/glad.c.o

glad/src/glad.i: glad/src/glad.c.i
.PHONY : glad/src/glad.i

# target to preprocess a source file
glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad/src/glad.c.i
.PHONY : glad/src/glad.c.i

glad/src/glad.s: glad/src/glad.c.s
.PHONY : glad/src/glad.s

# target to generate assembly for a file
glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad/src/glad.c.s
.PHONY : glad/src/glad.c.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_impl_glfw.o: imgui/imgui_impl_glfw.cpp.o
.PHONY : imgui/imgui_impl_glfw.o

# target to build an object file
imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_glfw.cpp.o
.PHONY : imgui/imgui_impl_glfw.cpp.o

imgui/imgui_impl_glfw.i: imgui/imgui_impl_glfw.cpp.i
.PHONY : imgui/imgui_impl_glfw.i

# target to preprocess a source file
imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_glfw.cpp.i
.PHONY : imgui/imgui_impl_glfw.cpp.i

imgui/imgui_impl_glfw.s: imgui/imgui_impl_glfw.cpp.s
.PHONY : imgui/imgui_impl_glfw.s

# target to generate assembly for a file
imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_glfw.cpp.s
.PHONY : imgui/imgui_impl_glfw.cpp.s

imgui/imgui_impl_glut.o: imgui/imgui_impl_glut.cpp.o
.PHONY : imgui/imgui_impl_glut.o

# target to build an object file
imgui/imgui_impl_glut.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_glut.cpp.o
.PHONY : imgui/imgui_impl_glut.cpp.o

imgui/imgui_impl_glut.i: imgui/imgui_impl_glut.cpp.i
.PHONY : imgui/imgui_impl_glut.i

# target to preprocess a source file
imgui/imgui_impl_glut.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_glut.cpp.i
.PHONY : imgui/imgui_impl_glut.cpp.i

imgui/imgui_impl_glut.s: imgui/imgui_impl_glut.cpp.s
.PHONY : imgui/imgui_impl_glut.s

# target to generate assembly for a file
imgui/imgui_impl_glut.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_glut.cpp.s
.PHONY : imgui/imgui_impl_glut.cpp.s

imgui/imgui_impl_opengl2.o: imgui/imgui_impl_opengl2.cpp.o
.PHONY : imgui/imgui_impl_opengl2.o

# target to build an object file
imgui/imgui_impl_opengl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_opengl2.cpp.o
.PHONY : imgui/imgui_impl_opengl2.cpp.o

imgui/imgui_impl_opengl2.i: imgui/imgui_impl_opengl2.cpp.i
.PHONY : imgui/imgui_impl_opengl2.i

# target to preprocess a source file
imgui/imgui_impl_opengl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_opengl2.cpp.i
.PHONY : imgui/imgui_impl_opengl2.cpp.i

imgui/imgui_impl_opengl2.s: imgui/imgui_impl_opengl2.cpp.s
.PHONY : imgui/imgui_impl_opengl2.s

# target to generate assembly for a file
imgui/imgui_impl_opengl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_opengl2.cpp.s
.PHONY : imgui/imgui_impl_opengl2.cpp.s

imgui/imgui_impl_opengl3.o: imgui/imgui_impl_opengl3.cpp.o
.PHONY : imgui/imgui_impl_opengl3.o

# target to build an object file
imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_opengl3.cpp.o
.PHONY : imgui/imgui_impl_opengl3.cpp.o

imgui/imgui_impl_opengl3.i: imgui/imgui_impl_opengl3.cpp.i
.PHONY : imgui/imgui_impl_opengl3.i

# target to preprocess a source file
imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_opengl3.cpp.i
.PHONY : imgui/imgui_impl_opengl3.cpp.i

imgui/imgui_impl_opengl3.s: imgui/imgui_impl_opengl3.cpp.s
.PHONY : imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_impl_opengl3.cpp.s
.PHONY : imgui/imgui_impl_opengl3.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Game"
	@echo "... glad"
	@echo "... imgui"
	@echo "... Core/Camera.o"
	@echo "... Core/Camera.i"
	@echo "... Core/Camera.s"
	@echo "... Core/EBO.o"
	@echo "... Core/EBO.i"
	@echo "... Core/EBO.s"
	@echo "... Core/FBO.o"
	@echo "... Core/FBO.i"
	@echo "... Core/FBO.s"
	@echo "... Core/Mesh.o"
	@echo "... Core/Mesh.i"
	@echo "... Core/Mesh.s"
	@echo "... Core/Model.o"
	@echo "... Core/Model.i"
	@echo "... Core/Model.s"
	@echo "... Core/Texture.o"
	@echo "... Core/Texture.i"
	@echo "... Core/Texture.s"
	@echo "... Core/VAO.o"
	@echo "... Core/VAO.i"
	@echo "... Core/VAO.s"
	@echo "... Core/VBO.o"
	@echo "... Core/VBO.i"
	@echo "... Core/VBO.s"
	@echo "... Core/shaderClass.o"
	@echo "... Core/shaderClass.i"
	@echo "... Core/shaderClass.s"
	@echo "... Core/stb/stb_image.o"
	@echo "... Core/stb/stb_image.i"
	@echo "... Core/stb/stb_image.s"
	@echo "... glad/src/glad.o"
	@echo "... glad/src/glad.i"
	@echo "... glad/src/glad.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_impl_glfw.o"
	@echo "... imgui/imgui_impl_glfw.i"
	@echo "... imgui/imgui_impl_glfw.s"
	@echo "... imgui/imgui_impl_glut.o"
	@echo "... imgui/imgui_impl_glut.i"
	@echo "... imgui/imgui_impl_glut.s"
	@echo "... imgui/imgui_impl_opengl2.o"
	@echo "... imgui/imgui_impl_opengl2.i"
	@echo "... imgui/imgui_impl_opengl2.s"
	@echo "... imgui/imgui_impl_opengl3.o"
	@echo "... imgui/imgui_impl_opengl3.i"
	@echo "... imgui/imgui_impl_opengl3.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

